function [m,covm]=wlsi_vary_lin1(x,y,vary,w)
% PERFORMS WEIGHTED LEAST-SQUARES INVERSION TO FIND A LINEAR FIT TO X VS Y
%
% CASE:
% - PREDICTORS X ARE ASSUMED KNOWN
% - OBSERVATIONS Y ARE ESTIMATED WITH VARIANCES ASSUMED KNOWN
% - VARIANCES OF OBSERVATIONS Y ARE ASSUMED TO BE NORMAL
% - VARIANCES OF OBSERVATIONS Y ARE NOT CONSTANT
% - OBSERVATIONS Y ARE ASSUMED TO HAVE NO COVARIANCE
% - Y IS ASSUMED TO BE A LINEAR FUNCTION OF X
% - SOME OBSERVATIONS Y ARE NOT TRUSTED

% MAKE COLUMN VECTORS
x=x(:);
y=y(:);
vary=vary(:);
w=w(:);

% NUMBER OF OBSERVATIONS
len=length(x);

% MAKE WEIGHTING MATRIX
W=sparse(1:len,1:len,w,len,len);

% KERNEL MATRIX (SOLVE FOR THE SLOPE AND INTERCEPT)
G=[x ones(len,1)];

% WEIGHTED LEAST SQUARES INVERSION (SAVING GENERALIZED INVERSE)
Gg=inv(G.'*W*G)*G.'*W;
m=Gg*y;

% SET UP DATA COVARIANCE MATRIX (ASSUME NO COVARIANCE)
covd=diag(vary.^2);

% FIND MODEL COVARIANCE MATRIX
covm=Gg*covd*Gg.';

end