function [m,covm]=wlsi_wvary_linn(x,y,vary,wp,n)
% PERFORMS WEIGHTED LEAST-SQUARES INVERSION TO FIND A POLY FIT TO X VS Y
%
% CASE:
% - PREDICTORS X ARE ASSUMED KNOWN
% - OBSERVATIONS Y ARE ESTIMATED WITH VARIANCES ASSUMED KNOWN
% - VARIANCES OF OBSERVATIONS Y ARE ASSUMED TO BE NORMAL
% - VARIANCES OF OBSERVATIONS Y ARE NOT CONSTANT
% - OBSERVATIONS Y ARE ASSUMED TO HAVE NO COVARIANCE
% - Y IS ASSUMED TO BE A POLYNOMIAL FUNCTION OF X OF ORDER N
% - HIGHLY VARIANT OBSERVATIONS Y ARE NOT TRUSTED
%
% NOTES:
% - WP = 0 IS UNWEIGHTED CASE

% MAKE COLUMN VECTORS
x=x(:);
y=y(:);
vary=vary(:);

% NUMBER OF OBSERVATIONS
len=length(x);

% MAKE WEIGHTING MATRIX (WEIGHTS ARE INVERSE OF VARIANCE TO THE WP POWER)
W=sparse(1:len,1:len,1/vary.^wp,len,len);

% KERNEL MATRIX (SOLVE FOR POLYNOMIAL ORDER N)
G=[x(:,ones(n,1)).^repmat(n:-1:1,len,1) ones(len,1)];

% WEIGHTED LEAST SQUARES INVERSION (SAVING GENERALIZED INVERSE)
Gg=inv(G.'*W*G)*G.'*W;
m=Gg*y;

% SET UP DATA COVARIANCE MATRIX (ASSUME NO COVARIANCE)
covd=diag(vary.^2);

% FIND MODEL COVARIANCE MATRIX
covm=Gg*covd*Gg.';

end