function [m,covm]=wlsi_cvary_lin1(x,y,w)
% PERFORMS WEIGHTED LEAST-SQUARES INVERSION TO FIND A LINEAR FIT TO X VS Y
%
% CASE:
% - PREDICTORS X ARE ASSUMED KNOWN
% - OBSERVATIONS Y ARE ESTIMATED WITH VARIANCES ASSUMED KNOWN
% - VARIANCES OF OBSERVATIONS Y ARE ASSUMED TO BE NORMAL
% - VARIANCES OF OBSERVATIONS Y ARE CONSTANT
% - OBSERVATIONS Y ARE ASSUMED TO HAVE NO COVARIANCE
% - Y IS ASSUMED TO BE A LINEAR FUNCTION OF X
% - SOME OBSERVATIONS Y ARE NOT TRUSTED
%
% NOTES:
% - MODEL COVARIANCE ASSUMES UNITY DATA VARIANCE

% MAKE COLUMN VECTORS
x=x(:);
y=y(:);
w=w(:);

% NUMBER OF OBSERVATIONS
len=length(x);

% MAKE WEIGHTING MATRIX
W=sparse(1:len,1:len,w,len,len);

% KERNEL MATRIX (SOLVE FOR THE SLOPE AND INTERCEPT)
G=[x ones(len,1)];

% WEIGHTED LEAST SQUARES INVERSION (SAVING GENERALIZED INVERSE)
Gg=inv(G.'*W*G)*G.'*W;
m=Gg*y;

% FIND MODEL COVARIANCE MATRIX
covm=Gg*Gg.';

end