function []=sz_toc_shortnames()
% Shortcut Function Names
%<a href="matlab:help addf">addf</a>    - ADDRECORDS                     - Add SEIZMO records
%<a href="matlab:help ch">ch</a>      - CHANGEHEADER                   - Change SEIZMO data header values
%<a href="matlab:help cmbmod">cmbmod</a>  - CMB_1DMODEL_LIBRARY            - Generates a library of CMB 1D Earth models
%<a href="matlab:help cmph">cmph</a>    - COMPAREHEADER                  - List SEIZMO headers side-by-side for easy comparison
%<a href="matlab:help cstf">cstf</a>    - CONVOLVE_SOURCE_TIMEFUNCTION   - Convolve source function on SEIZMO records
%<a href="matlab:help dstf">dstf</a>    - DECONVOLVE_SOURCE_TIMEFUNCTION - Deconvolve source from SEIZMO records
%<a href="matlab:help dif">dif</a>     - DIFFERENTIATE                  - Differentiate SEIZMO records
%<a href="matlab:help div">div</a>     - DIVIDE                         - Divide SEIZMO records by a constant
%<a href="matlab:help divo">divo</a>    - OMEGADIVIDE                    - Integrate SEIZMO records in the frequency domain
%<a href="matlab:help divf">divf</a>    - DIVIDERECORDS                  - Divide SEIZMO records
%<a href="matlab:help gh">gh</a>      - GETHEADER                      - Get SEIZMO data header values
%<a href="matlab:help gpoly">gpoly</a>   - GETPOLYNOMIAL                  - Get polynomial fit to SEIZMO records
%<a href="matlab:help joinf">joinf</a>   - JOINRECORDS                    - Join SEIZMO records into multiple-component record(s)
%<a href="matlab:help lh">lh</a>      - LISTHEADER                     - List SEIZMO data headers
%<a href="matlab:help mstf">mstf</a>    - MAKE_SOURCE_TIMEFUNCTION       - Returns source time functions for convolution
%<a href="matlab:help mul">mul</a>     - MULTIPLY                       - Multiply SEIZMO records by a constant
%<a href="matlab:help mulo">mulo</a>    - OMEGAMULTIPLY                  - Differentiate SEIZMO records in the frequency domain
%<a href="matlab:help mulf">mulf</a>    - MULTIPLYRECORDS                - Multiply SEIZMO records
%<a href="matlab:help p0">p0</a>      - PLOT0                          - Plot SEIZMO data records in an evenly spaced record section
%<a href="matlab:help p1">p1</a>      - PLOT1                          - Plot SEIZMO data records in individual subplots
%<a href="matlab:help p2">p2</a>      - PLOT2                          - Overlay plot of SEIZMO data records
%<a href="matlab:help pspec0">pspec0</a>  - PLOTSPECTRA0                   - Evenly spaced plot of SEIZMO data record spectra
%<a href="matlab:help pspec1">pspec1</a>  - PLOTSPECTRA1                   - Plot SEIZMO data record spectra in individual subplots
%<a href="matlab:help pspec2">pspec2</a>  - PLOTSPECTRA2                   - Overlay plot of SEIZMO data record spectra
%<a href="matlab:help qh">qh</a>      - QUERYHEADER                    - List SEIZMO headers side-by-side for easy comparison
%<a href="matlab:help qsnr">qsnr</a>    - QUICKSNR                       - Quick estimation of SNR for SEIZMO records
%<a href="matlab:help rd">rd</a>      - READDATA                       - Read SEIZMO data from datafiles
%<a href="matlab:help rdw">rdw</a>     - READDATAWINDOW                 - Read data window into SEIZMO data structure
%<a href="matlab:help rh">rh</a>      - READHEADER                     - Read header info from SEIZMO datafiles
%<a href="matlab:help r">r</a>       - READSEIZMO                     - Read datafiles into SEIZMO data structure
%<a href="matlab:help recsec">recsec</a>  - RECORDSECTION                  - Plots SEIZMO data records in a distance spaced record section
%<a href="matlab:help rdead">rdead</a>   - REMOVEDEADRECORDS              - Removes constant SEIZMO records
%<a href="matlab:help rdupes">rdupes</a>  - REMOVEDUPLICATES               - Remove duplicate SEIZMO records
%<a href="matlab:help rmean">rmean</a>   - REMOVEMEAN                     - Remove mean from SEIZMO records
%<a href="matlab:help rpoly">rpoly</a>   - REMOVEPOLYNOMIAL               - Remove polynomial trend from SEIZMO records
%<a href="matlab:help rtr">rtr</a>     - REMOVETREND                    - Remove linear trend from SEIZMO records
%<a href="matlab:help rev">rev</a>     - REVERSE                        - Reverse SEIZMO records
%<a href="matlab:help specsec">specsec</a> - SPECTRASECTION                 - Plots SEIZMO data record spectra in a record section
%<a href="matlab:help deci">deci</a>    - SQUISH                         - Downsample SEIZMO records by an integer factor
%<a href="matlab:help sub">sub</a>     - SUBTRACT                       - Subtract a constant from SEIZMO records
%<a href="matlab:help subf">subf</a>    - SUBTRACTRECORDS                - Subtract SEIZMO records
%<a href="matlab:help sync">sync</a>    - SYNCHRONIZE                    - Synchronizes the reference times of SEIZMO records
%<a href="matlab:help syncsr">syncsr</a>  - SYNCRATES                      - Resample SEIZMO records to a common sample rate
%<a href="matlab:help wh">wh</a>      - WRITEHEADER                    - Write SEIZMO data header info to datafiles
%<a href="matlab:help w">w</a>       - WRITESEIZMO                    - Write SEIZMO records to datafile
%
% <a href="matlab:help seizmo">SEIZMO - Passive Seismology Toolbox</a>
end
