function []=sz_toc_response()
% Instrument Response Functions
%<a href="matlab:help applysacpz">applysacpz</a>           - Applies SAC PoleZero responses to SEIZMO records
%<a href="matlab:help bad_sacpz">bad_sacpz</a>            - Finds SAC Polezero files with bad responses
%<a href="matlab:help fix_bad_sacpz">fix_bad_sacpz</a>        - Fixes SOME cases of bad SAC PoleZeros
%<a href="matlab:help fix_old_sacpz">fix_old_sacpz</a>        - Converts old SEIZMO SAC PoleZero info to new format
%<a href="matlab:help gensacpzname">gensacpzname</a>         - Generates SAC Polezero names based on sacpzdb info
%<a href="matlab:help getsacpz">getsacpz</a>             - Finds, reads and adds SAC PoleZero info into a SEIZMO struct
%<a href="matlab:help iris_sacpzdb_build">iris_sacpzdb_build</a>   - Creates the IRIS SAC PoleZero Database
%<a href="matlab:help iris_sacpzdb_fixes">iris_sacpzdb_fixes</a>   - Notes on fixes made to IRIS SAC PoleZero responses
%<a href="matlab:help issacpz_rdseed">issacpz_rdseed</a>       - Returns TRUE if input is a SAC PoleZero RDSEED struct
%<a href="matlab:help makesacpzdb">makesacpzdb</a>          - Makes a SAC PoleZero database using a list of directories
%<a href="matlab:help parse_sacpz_filename">parse_sacpz_filename</a> - Parses info in the SAC PoleZero filename
%<a href="matlab:help readsacpz">readsacpz</a>            - Reads in a SAC PoleZero file
%<a href="matlab:help readsacpz_rdseed">readsacpz_rdseed</a>     - Reads in SAC polezero files generated by RDSEED
%<a href="matlab:help removesacpz">removesacpz</a>          - Removes SAC PoleZero responses from SEIZMO records
%<a href="matlab:help writesacpz">writesacpz</a>           - Writes out a SAC PoleZero file
%<a href="matlab:help writesacpz_rdseed">writesacpz_rdseed</a>    - Writes SAC polezero files equivalent to RDSEED
%<a href="matlab:help zpk2ap">zpk2ap</a>               - Zeros-Poles-Constant to Amplitude & Phase
%<a href="matlab:help zpk2cmplx">zpk2cmplx</a>            - Zeros-Poles-Constant to Complex Spectra
%
% <a href="matlab:help seizmo">SEIZMO - Passive Seismology Toolbox</a>
end
