#!/bin/bash
echo 'Number of Personal m-Files:'
ls -1 *.m cmap/*.m cmt/*.m event/*.m fixes/*.m fk/*.m gui/*.m invert/*.m mattaup/*.m misc/*.m models/*.m noise/*.m position/*.m private/*.m response/*.m sphpoly/*.m synth/*.m time/*.m tomo/*.m topo/*.m tpw/*.m ttcorrect/*.m ww3/*.m xcalign/*.m | wc -l
echo 'Number of Additional m-Files:'
ls -1 external/*.m m_map/1.4e/*.m m_map/1.4e/private/*.m | wc -l
echo 'Total Number of Lines (Personal):'
cat *.m cmap/*.m cmt/*.m event/*.m fixes/*.m fk/*.m gui/*.m invert/*.m mattaup/*.m misc/*.m models/*.m noise/*.m position/*.m private/*.m response/*.m sphpoly/*.m synth/*.m time/*.m tomo/*.m topo/*.m tpw/*.m ttcorrect/*.m ww3/*.m xcalign/*.m | wc -l
echo 'Total Number of Words (Personal):'
cat *.m cmap/*.m cmt/*.m event/*.m fixes/*.m fk/*.m gui/*.m invert/*.m mattaup/*.m misc/*.m models/*.m noise/*.m position/*.m private/*.m response/*.m sphpoly/*.m synth/*.m time/*.m tomo/*.m topo/*.m tpw/*.m ttcorrect/*.m ww3/*.m xcalign/*.m | wc -w
echo 'Total Number of Characters (Personal):'
cat *.m cmap/*.m cmt/*.m event/*.m fixes/*.m fk/*.m gui/*.m invert/*.m mattaup/*.m misc/*.m models/*.m noise/*.m position/*.m private/*.m response/*.m sphpoly/*.m synth/*.m time/*.m tomo/*.m topo/*.m tpw/*.m ttcorrect/*.m ww3/*.m xcalign/*.m | wc -c

