function [P]=plotdef()
%
%    Usage:
%
%    Description:
%
%    Notes:
%
%    Examples:
%
%    See also:

%     Version History:
%        Aug. 20, 2009 - initial version
%
%     Written by Garrett Euler (ggeuler at wustl dot edu)
%     Last Updated Aug. 20, 2009 at 21:15 GMT

% todo:
% - what are all the externally handled groups
% - 

P.PLOTGENERAL=struct(...
...% Externally Handled
'FIGURE',{},...
'AXES',{'ticklength',[0 0],'box','on'},...
'LEGEND',{'location','best'},...
'MARKER',{'color',[0.5 0.5 0.5]},...
'MARKERLABEL',{'verticalalignment','top'},...
'AMARKER',{'color','g'},...
'FMARKER',{'color','r'},...
'OMARKER',{'color',[1 0.5 0]},...
...% Function Handled
'SHOWMARKERS',true,...
'SHOWMARKERLABELS',true,...
'SHOWLEGEND',false,...
'GRID','on',...
'NORMALIZE',true,...
'NORMSTYLE','group',...
'NORMMAX',0.1,...
...% Expanded
'BGCOLOR','k',...
'FGCOLOR','w',...
'COLORMAP','hsv',...
'FONTUNITS','normalized',...
'FONTSIZE',0.02...
);
P.PLOT0=struct(...
...% Externally Handled
...% Function Handled
'NAMESONYAXIS',false...
);
P.PLOT1=struct(...
...% Externally Handled
...% Function Handled
'NORMALIZE',false...
);
P.PLOT2=struct(...
...% Externally Handled
...% Function Handled
'NORMALIZE',false...
);
P.PLOTDENDRO=struct(...
...% Externally Handled
...% Function Handled
'TREEORIENTATION','left',...         % DIRECTION TREE NARROWS
'TREEDEFAULTCOLOR',[0.5 0.5 0.5],... % DEFAULT COLORING OF TREE
'TREECOLORTHRESHOLD',0.03,...        % (DIS)SIMILARITY LIMIT
'MARKERCOLOR','r',...                % (DIS)SIMILARITY LIMIT MARKER COLOR
'SIMILARITY',false...                % PLOT X-AXIS AS SIMILARITY
...                                  %  (FALSE = DISSIMILARITY)
);
P.RECSEC=struct(...
...% Externally Handled
...% Function Handled
'YFIELD','gcarc'...
);

end
